const Appication = require("./App")
const Loan = require("./entities/Loan")

const App = new Appication()

App.createUser('Arthur', 'arthuraadeoliveira@gmail.com')
App.createUser('Arthur', 'arthuraadeoliveira@gmail.com')
App.createUser('Maria', 'malualdb@gmail.com')
App.getUsers
App.getUserByEmail('arthuraadeoliveira@gmail.com')
App.changeTax(4)
Loan.tax
App.newDeposit('arthuraadeoliveira@gmail.com', 1000)
App.newDeposit('arthuraadeoliveira@gmail.com', 10000)
App.getUserByEmail('arthuraadeoliveira@gmail.com')
App.transfer('arthuraadeoliveira@gmail.com',1000,'Maria')
App.showExtract('arthuraadeoliveira@gmail.com')
App.showAmount('arthuraadeoliveira@gmail.com')
App.showExtract('malualdb@gmail.com')
App.showAmount('malualdb@gmail.com')
App.newLoan('arthuraadeoliveira@gmail.com',1200,3)
App.newLoan('arthuraadeoliveira@gmail.com',1200,3)
App.showExtract('arthuraadeoliveira@gmail.com')
App.showAmount('arthuraadeoliveira@gmail.com')
App.showInstallment('arthuraadeoliveira@gmail.com')
App.payLoan('arthuraadeoliveira@gmail.com')
App.showInstallment('arthuraadeoliveira@gmail.com')
App.showAmount('arthuraadeoliveira@gmail.com')
App.payLoan('arthuraadeoliveira@gmail.com')
App.showInstallment('arthuraadeoliveira@gmail.com')
App.showAmount('arthuraadeoliveira@gmail.com')
App.payLoan('arthuraadeoliveira@gmail.com')
App.showInstallment('arthuraadeoliveira@gmail.com')
App.showAmount('arthuraadeoliveira@gmail.com')